### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by siraben** [acrogenesis/nyt-today#1]
Thanks for making this, it's wonderful to have in conjunction with [remarkable_news](https://github.com/Evidlo/remarkable_news). Looks like [the site](https://nyt-today.acrogenesis.com/nyt) is down, I'm getting HTTP code 0.

**Comment by acrogenesis** [comment]
Thanks for reporting I’ll check it out

**Comment by acrogenesis** [comment]
@siraben It seems its a problem with dns on the client side. I flushed the DNS and it started working.

**Comment by siraben** [comment]
Thank you, resolved.

**Comment by siraben** [comment]
Reopening because it seems like it's down again.

**Comment by acrogenesis** [comment]
@siraben it seems the website where we were getting the pdf has been removed https://static01.nyt.com/images/$TODAY/nytfrontpage/scan.pdf

**Comment by acrogenesis** [comment]
I've fixed it 👍 thanks
