### ISSUE TITLE
Is this still working? I am getting access denied from the url

### ISSUE THREAD

**Issue by skynet01** [acrogenesis/nyt-today#2]
I tried hitting the url directly and I get the access denied XML:
https://static01.nyt.com/images/2022/08/11/nytfrontpage/scan.pdf

I did find an alternative location though...
https://cdn.freedomforum.org/dfp/pdf11/NY_NYT.pdf

...but the bottom is a bit cut off

**Comment by acrogenesis** [comment]
Hi @skynet01 I can access it correctly right now. Maybe you're using a vpn or proxy the website isn't liking.

**Comment by skynet01** [comment]
Hmm strange.. as soon as I turned ON the vpn it started working. 😄
With VPN off using Comcast internet provider I get this:
![image](https://user-images.githubusercontent.com/8117544/184274387-34a64ad6-30f7-47d4-a20c-06dc8a81651a.jpeg)

I apologize for bothering you about this. Didn't think of checking the most obvious. You can close it and ill see what happened on my end.

**Comment by skynet01** [comment]
closing it

**Comment by skynet01** [comment]
Closing it
